#!/bin/bash
SOURCE=$1
TARGET=${SOURCE%%.tif}_arch.tif
gdalwarp --config GDAL_CACHEMAX 800 -r cubic -t_srs epsg:4326 $SOURCE tmp.tif
GDAL_TIFF_INTERNAL_MASK=YES gdal_translate -co TILED=YES -co COMPRESS=JPEG -co PHOTOMETRIC=YCBCR -b 1 -b 2 -b 3 -mask 4 tmp.tif $TARGET
rm tmp.tif
gdaladdo -r average $TARGET 2 4 8 16 32 64
