#!/usr/bin/env python

import sys, os
import urlgrabber, urlgrabber.progress
import oam

def fetch_image_files(layer, opts):
    if opts.layer:
        path = str(opts.layer)
        if not opts.test and not os.path.isdir(path):
            os.makedirs(path)
    else:
        path = "."
    for image in layer["images"]:
        filetype = image["url"].split(".")[-1]
        target = os.path.join(path, image["hash"] + "." + filetype)
        if opts.test:
            print >>sys.stderr, image["url"], "->", target
        else:
            meter = urlgrabber.progress.text_progress_meter()
            urlgrabber.urlgrab(image["url"], target, progress_obj=meter)

def run_gdalbuildvrt(opts):
    layer_id = str(opts.layer)
    glob = os.path.join(layer_id, "*.*")
    os.system("gdalbuildvrt %s.vrt %s" % (layer_id, glob))

if __name__ == "__main__":
    parser = oam.parse_options()
    opts, args = parser.parse_args()
    bbox = oam.parse_bbox(args)
    client = oam.build_client(opts)
    fetch_image_files(client, bbox, opts)
    run_gdalbuildvrt(opts)
